[package]
name = "RCompiler-2025"
version = "0.1.0"
edition = "2024"

[dependencies]
libc = "0.2.177"
regex = "1.11.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.142"
tempfile = "3.23.0"
thiserror = "2.0.12"
